services:
  traefik:
    image: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/traefik.yml:ro"
      - traefik-dynamic:/etc/traefik/dynamic
      - letsencrypt:/letsencrypt
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  traefik-dynamic:
    external: true
  letsencrypt: