api:
  dashboard: true
  disabledashboardad: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: resolver



providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  resolver:
    acme:
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

accessLog: {}