services:
  dokuwiki:
    volumes:
      - ./data:/storage
    image: dokuwiki/dokuwiki:stable
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.docuwiki.entrypoints=web,websecure"
      - "traefik.http.routers.docuwiki.rule=Host(`wiki.dabney.house`)"
      - "traefik.http.services.docuwiki.loadbalancer.server.port=8080"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true