services:
  nginx:
    image: ghcr.io/dabneyhovse/landing
    security_opt:
      - no-new-privileges:true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web-nginx.entrypoints=web,websecure"
      - "traefik.http.routers.web-nginx.rule=Host(`dabney.house`)"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true